export interface ecRates {
  currency: string
  rates: Rates
}

export interface Rates {
  AED?: string
  AFN?: string
  ALL?: string
  AMD?: string
  ANG?: string
  AOA?: string
  ARS?: string
  AWG?: string
  AZN?: string
  BAM?: string
  BBD?: string
  BDT?: string
  BGN?: string
  BHD?: string
  BIF?: string
  BMD?: string
  BND?: string
  BOB?: string
  BRL?: string
  BSD?: string
  BTN?: string
  BWP?: string
  BYN?: string
  BYR?: string
  BZD?: string
  CAD?: string
  CDF?: string
  CHF?: string
  CLF?: string
  CLP?: string
  CNY?: string
  COP?: string
  CRC?: string
  CUC?: string
  CVE?: string
  CZK?: string
  DJF?: string
  DKK?: string
  DOP?: string
  DZD?: string
  EGP?: string
  ETB?: string
  EUR?: string
  FJD?: string
  FKP?: string
  GBP?: string
  GEL?: string
  GHS?: string
  GIP?: string
  GMD?: string
  GNF?: string
  GTQ?: string
  GYD?: string
  HKD?: string
  HNL?: string
  HRK?: string
  HTG?: string
  HUF?: string
  IDR?: string
  ILS?: string
  INR?: string
  IQD?: string
  ISK?: string
  JMD?: string
  JOD?: string
  JPY?: string
  KES?: string
  KGS?: string
  KHR?: string
  KMF?: string
  KRW?: string
  KWD?: string
  KYD?: string
  KZT?: string
  LAK?: string
  LBP?: string
  LKR?: string
  LRD?: string
  LSL?: string
  LYD?: string
  MAD?: string
  MDL?: string
  MGA?: string
  MKD?: string
  MMK?: string
  MNT?: string
  MOP?: string
  MRO?: string
  MUR?: string
  MVR?: string
  MWK?: string
  MXN?: string
  MYR?: string
  MZN?: string
  NAD?: string
  NGN?: string
  NIO?: string
  NOK?: string
  NPR?: string
  NZD?: string
  OMR?: string
  PAB?: string
  PEN?: string
  PGK?: string
  PHP?: string
  PKR?: string
  PLN?: string
  PYG?: string
  QAR?: string
  RON?: string
  RSD?: string
  RUB?: string
  RWF?: string
  SAR?: string
  SBD?: string
  SCR?: string
  SDG?: string
  SEK?: string
  SHP?: string
  SKK?: string
  SLL?: string
  SOS?: string
  SRD?: string
  STD?: string
  SVC?: string
  SZL?: string
  THB?: string
  TJS?: string
  TMT?: string
  TND?: string
  TOP?: string
  TRY?: string
  TTD?: string
  TWD?: string
  TZS?: string
  UAH?: string
  UGX?: string
  UYU?: string
  UZS?: string
  VES?: string
  VND?: string
  VUV?: string
  WST?: string
  XAF?: string
  XAG?: string
  XAU?: string
  XCD?: string
  XOF?: string
  XPD?: string
  XPF?: string
  XPT?: string
  YER?: string
  ZAR?: string
  ZMK?: string
  ZMW?: string
  JEP?: string
  GGP?: string
  IMP?: string
  CNH?: string
  EEK?: string
  LTL?: string
  LVL?: string
  TMM?: string
  ZWD?: string
  VEF?: string
  SGD?: string
  AUD?: string
  USD?: string
  BTC?: string
  BCH?: string
  BSV?: string
  ETH?: string
  ETH2?: string
  ETC?: string
  LTC?: string
  ZRX?: string
  USDC?: string
  BAT?: string
  LOOM?: string
  MANA?: string
  KNC?: string
  LINK?: string
  DNT?: string
  MKR?: string
  CVC?: string
  OMG?: string
  GNT?: string
  DAI?: string
  SNT?: string
  ZEC?: string
  XRP?: string
  REP?: string
  XLM?: string
  EOS?: string
  XTZ?: string
  ALGO?: string
  DASH?: string
  ATOM?: string
  OXT?: string
  COMP?: string
  ENJ?: string
  REPV2?: string
  BAND?: string
  NMR?: string
  CGLD?: string
  UMA?: string
  LRC?: string
  YFI?: string
  UNI?: string
  BAL?: string
  REN?: string
  WBTC?: string
  NU?: string
  YFII?: string
  FIL?: string
  AAVE?: string
  BNT?: string
  GRT?: string
  SNX?: string
  STORJ?: string
  SUSHI?: string
  MATIC?: string
  SKL?: string
  ADA?: string
  ANKR?: string
  CRV?: string
  ICP?: string
  NKN?: string
  OGN?: string
  '1INCH'?: string
  USDT?: string
  FORTH?: string
  CTSI?: string
  TRB?: string
  POLY?: string
  MIR?: string
  RLC?: string
  DOT?: string
  SOL?: string
  DOGE?: string
  MLN?: string
  GTC?: string
  AMP?: string
  SHIB?: string
  CHZ?: string
  KEEP?: string
  LPT?: string
  QNT?: string
  BOND?: string
  RLY?: string
  CLV?: string
  FARM?: string
  MASK?: string
  ANT?: string
  FET?: string
  PAX?: string
  ACH?: string
  ASM?: string
  PLA?: string
  RAI?: string
  TRIBE?: string
  ORN?: string
  IOTX?: string
  UST?: string
  QUICK?: string
  AXS?: string
  REQ?: string
  WLUNA?: string
  TRU?: string
  RAD?: string
  COTI?: string
  DDX?: string
  SUKU?: string
  RGT?: string
  XYO?: string
  ZEN?: string
  AST?: string
  AUCTION?: string
  BUSD?: string
  JASMY?: string
  WCFG?: string
  BTRST?: string
  AGLD?: string
  AVAX?: string
  FX?: string
  TRAC?: string
  LCX?: string
  ARPA?: string
  BADGER?: string
  KRL?: string
  PERP?: string
  RARI?: string
  DESO?: string
  API3?: string
  NCT?: string
  SHPING?: string
  UPI?: string
  CRO?: string
  MTL?: string
  ABT?: string
  CVX?: string
  AVT?: string
  MDT?: string
  VGX?: string
  ALCX?: string
  COVAL?: string
  FOX?: string
  MUSD?: string
  CELR?: string
  GALA?: string
  POWR?: string
  GYEN?: string
  ALICE?: string
  INV?: string
  LQTY?: string
  PRO?: string
  SPELL?: string
  ENS?: string
  DIA?: string
  BLZ?: string
  CTX?: string
  ERN?: string
  IDEX?: string
  MCO2?: string
  POLS?: string
  SUPER?: string
  UNFI?: string
  STX?: string
  KSM?: string
  GODS?: string
  IMX?: string
  RBN?: string
  BICO?: string
  GFI?: string
  ATA?: string
  GLM?: string
  MPL?: string
  PLU?: string
  SWFTC?: string
  SAND?: string
  OCEAN?: string
  GNO?: string
  FIDA?: string
  ORCA?: string
  CRPT?: string
  QSP?: string
  RNDR?: string
  NEST?: string
  PRQ?: string
  HOPR?: string
  JUP?: string
  MATH?: string
  SYN?: string
  AIOZ?: string
  WAMPL?: string
  AERGO?: string
  INDEX?: string
  TONE?: string
  HIGH?: string
  GUSD?: string
  FLOW?: string
  ROSE?: string
  OP?: string
  APE?: string
  MINA?: string
  MUSE?: string
  SYLO?: string
  CBETH?: string
  DREP?: string
  ELA?: string
  FORT?: string
  ALEPH?: string
  DEXT?: string
  FIS?: string
  BIT?: string
  GMT?: string
  GST?: string
  MEDIA?: string
  C98?: string
  ARB?: string
  TIME?: string
  RPL?: string
  MXC?: string
  HBAR?: string
  KAVA?: string
  SPA?: string
  EGLD?: string
  GHST?: string
  NEAR?: string
  INJ?: string
  AUDIO?: string
  MONA?: string
  TVK?: string
  POND?: string
  DYP?: string
  LDO?: string
  LIT?: string
  XMON?: string
  ILV?: string
  PUNDIX?: string
  PYR?: string
  PNG?: string
  METIS?: string
  RARE?: string
  QI?: string
  MSOL?: string
  OSMO?: string
  XCN?: string
  DAR?: string
  MAGIC?: string
  AURORA?: string
  BOBA?: string
  VOXEL?: string
  OOKI?: string
  MULTI?: string
  LOKA?: string
  T?: string
  MNDE?: string
  STG?: string
  GAL?: string
  '00'?: string
  HFT?: string
  DIMO?: string
  EUROC?: string
  BLUR?: string
  APT?: string
  WAXL?: string
  LSETH?: string
  SUI?: string
  AXL?: string
  ACS?: string
  FLR?: string
  PRIME?: string
}
